version: 2
jobs:
  build:

    working_directory: ~/circleci-telegram-bot

    docker:
    - image: circleci/openjdk:8-jdk-browsers
    - image: circleci/mysql:8.0.11
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_HOST: 127.0.0.1
    steps:

    - checkout

    - restore_cache:
        key: circleci-telegram-bot-{{ checksum "pom.xml" }}

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: circleci-telegram-bot-{{ checksum "pom.xml" }}

    - run: mvn clean install

    - store_test_results:
        path: target/surefire-reports

    - store_artifacts:
        path: target/telegram-bot-1.0.jar