version: 2
jobs:
  build:

    working_directory: ~/circleci-telegram-bot

    docker:
    - image: circleci/openjdk:8-jdk-browsers
    - image: circleci/mysql:8.0.11
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_DATABASE=: zayets_bot
    steps:

    - checkout

    - restore_cache:
        key: circleci-telegram-bot-{{ checksum "pom.xml" }}

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: circleci-telegram-bot-{{ checksum "pom.xml" }}

    - run:
        name: Wait for DB
        # preinstalled in circleci/* docker image
        command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

    - run: mvn clean install

    - store_test_results:
        path: target/surefire-reports

    - store_artifacts:
        path: target/telegram-bot-1.0.jar